// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSai65h9cIXY3xA6fKah7cUwHbir1IDUY',
    appId: '1:18368641339:web:51336aa0aeba9f48cbdf1e',
    messagingSenderId: '18368641339',
    projectId: 'portfolio-tracker-4034e',
    authDomain: 'portfolio-tracker-4034e.firebaseapp.com',
    storageBucket: 'portfolio-tracker-4034e.firebasestorage.app',
    measurementId: 'G-L8DVM4T6J7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBz6sVzftfakViFWuq6eZF-qTQWmBxSxNs',
    appId: '1:18368641339:android:884528b14dba1a7ccbdf1e',
    messagingSenderId: '18368641339',
    projectId: 'portfolio-tracker-4034e',
    storageBucket: 'portfolio-tracker-4034e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdICJecMQ9FNnQ5xsWDJE41Zw1TDE-O2Y',
    appId: '1:18368641339:ios:0d0a96102fc563f9cbdf1e',
    messagingSenderId: '18368641339',
    projectId: 'portfolio-tracker-4034e',
    storageBucket: 'portfolio-tracker-4034e.firebasestorage.app',
    iosBundleId: 'com.example.portfolioTracker',
  );
}
